#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_3x6_3(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, SC_SENT, KC_LCTL, MT(MOD_LGUI, KC_ENT), MO(1), MO(2), KC_SPC, KC_LALT),
                                                              [1] = LAYOUT_split_3x6_3(KC_DEL, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_BSPC, KC_LCTL, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TILD, KC_MINS, KC_EQL, KC_LCBR, KC_RCBR, KC_BSLS, KC_LSFT, KC_6, KC_7, KC_8, KC_9, KC_0, KC_GRV, KC_UNDS, KC_PLUS, KC_LBRC, KC_RBRC, SC_SENT, KC_NO, KC_NO, KC_NO, KC_CAPS, KC_SPC, KC_LALT),
                                                              [2] = LAYOUT_split_3x6_3(KC_TAB, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_LALT, TG(3), KC_NO, KC_VOLD, KC_VOLU, KC_MUTE, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_F12, KC_LSFT, KC_NO, KC_NO, KC_MPRV, KC_MNXT, KC_MPLY, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_NO, SC_SENT, KC_LCTL, KC_ENT, KC_LGUI, KC_NO, KC_NO, KC_NO),
                                                              [3] = LAYOUT_split_3x6_3(KC_TAB, TG(3), KC_NO, KC_NO, KC_NO, QK_BOOT, KC_PLUS, KC_7, KC_8, KC_9, KC_MINS, KC_NO, KC_ESC, KC_NO, RGB_HUI, RGB_SAI, RGB_VAI, RGB_TOG, KC_ASTR, KC_4, KC_5, KC_6, KC_SLSH, KC_NO, KC_LSFT, KC_NO, RGB_HUD, RGB_SAD, RGB_VAD, RGB_MOD, KC_EQL, KC_1, KC_2, KC_3, KC_COMM, KC_NO, KC_LCTL, KC_ENT, KC_LALT, KC_NO, KC_SPC, KC_0)};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
